### PR TITLE
final rename of "reusable relay" classes

### PR DESCRIPTION
**Pull request by pmjones**
The changes are:
1. Rename Relay to Runner,
2. Rename RelayFactory to RunnerFactory,
3. Rename ReusableRelay to Relay,
4. Remove the existing RelayBuilder, and
5. Rename ReusableRelayBuilder to RelayBuilder.

The renames have the effect of making a Relay reusable by default, and the Runner the single-use dispatcher that the Relay uses.

Also added docblocks.

### CODE REVIEW

**Comment by pmjones** [comment]
@shadowhand The renames make the diff look messy, but that really is the only substantial change.

**Comment by shadowhand** [comment]
Looks good. I'm still not entirely sure how this will play out when implemented (outside of tests), but I trust it works better.

**Comment by pmjones** [comment]
All righty. Here's the plan. I'm going to tag the existing 1.x as 0.2.0, so you can lock to that without fear of breaks. Then I will merge this branch and update the related docs on the site, and you can transition at your leisure. Reasonable?

**Comment by dolfelt** [comment]
@pmjones That's fine. We aren't currently using Relay in our master branch, so I'll just update our code to support these changes.

**Comment by pmjones** [comment]
Good deal; thanks for letting me know.

**Pull request merged**
