### PR TITLE
Reusable Relay objects, and client-related logic

### PR DESCRIPTION
**Pull request by pmjones**
This BC-breaking PR opens up Relay to client-related usage as well as server-related usage.

The central break is that what used to be the _Relay_ class is now the _Runner_ class, and a replacement _Relay_ class now acts as reusable wrapper around Runner instances.  That means the new _Relay_ class is instantiated differently.
- Relay now typehints on _RequestInterface_ instead of _ServerRequestInterface_. Because the latter extends the former, this means _Relay_ can now be used for HTTP client logic as well.
- You should now create the _Relay_ object from the _RelayBuilder_ instead of creating it directly. If you create it directly, you will need to pass a _RunnerFactory_ to the constructor instead of a `$resolver`.
- _Relay_ objects are now reusable; i.e., they will reuse the $queue if you dispatch through them again.
- If you know you want to dispatch the middleware queue only once, you can save some minor overhead by instantiating a _Runner_ instead of a _Relay_. E.g., `$runner = new Runner($queue, $resolver); $response = $runner($request, $response);`.

### CODE REVIEW

**Comment by shadowhand** [comment]
I'm not sure I entirely understand the benefits of this change, other being able to run the queue more than once. Could you speak a little more to intent of these changes?

**Comment by pmjones** [comment]
@shadowhand, you have summed it up neatly. Running it more than once is exactly the intent, specifically in relation to async server-side operations, and to client-related operations. It is born of issue #5 which convinced me, after a bit, that it would be a useful addition.

(updated to point to issue #5 instead of PR #7)

**Comment by shadowhand** [comment]
Okay, I would suggest breaking this up into separate PRs, as there is a significant mixing of concerns right now.

One PR should address the reusable queue.
One PR modifies the interfaces.
One PR sets up the factory methods.

Right now it is hard to evaluate these changes independently or provide useful feedback.

**Comment by pmjones** [comment]
That's fair, and will do.

**Comment by pmjones** [comment]
Closing in favor of separate PRs as recommended by @shadowhand .

**Comment by pmjones** [comment]
@shadowhand: first new PR is #8

**Pull request closed without merging**
