### PR TITLE
Support for PSR-15 RequestHandlerInterface for queue items

### PR DESCRIPTION
**Pull request by wirebox-platform**
Problem/details/solution noted here:
https://github.com/relayphp/Relay.Relay/issues/47

### CODE REVIEW

**Comment by wirebox-platform** [comment]
re "All checks have failed" - looks like an issue with the CI & PHP version, rather than my PR itself?

**Comment by cxj** [comment]
The `.travis.yml` file needs to be updated to provide a workable test environment.  You can append commits to your PR to fix this yourself, if so inclined.

I'm not sure why the PHP 7.2 requirement was reverted back in March.  7.1 active support ended last December and security patches for 7.1 end in December of this year.  So really, any actively supported PHP project should be targeting only PHP versions 7.2 and 7.3 at this time.  Maybe @kevinsmith  can comment and clarify his thinking on this.

**Comment by wirebox-platform** [comment]
Yeah, can't work it out. Seems like Travis installs the right version of PHPUnit but then uses a different one...

```
  - Installing phpunit/phpunit (7.5.15): Downloading (100%)


$ phpunit --coverage-clover=coverage.clover
PHPUnit 8.0.4 by Sebastian Bergmann and contributors.
```

**Comment by wirebox-platform** [comment]
Done it. Seems there's a global phpunit bin on there @ version 8, so changed the script to use the vendor/bin/phpunit one explicitly. Now works & passes the checks :)

**Comment by cxj** [comment]
Looks good.

**Comment by kevinsmith** [comment]
Everything looks good to me, it just needs a test. @wirebox-platform, if you just want to copy over the test I wrote for #49, that should do it:

https://github.com/relayphp/Relay.Relay/blob/30419323302d5e6a15ed88a6cd0c0fb7ac66ea6c/tests/RelayTest.php#L88-L100

**Comment by wirebox-platform** [comment]
all done :)

**Comment by wirebox-platform** [comment]
@kevinsmith  all done :)

**Comment by kevinsmith** [comment]
Thank you, @wirebox-platform!

**Pull request merged**
