### PR TITLE
There is always a $next middleware to be called

### PR DESCRIPTION
**Pull request by renan**
Looking at the code I don't see how `$next` could ever be `null`

### CODE REVIEW

**Comment by pmjones** [comment]
@renan You look to be correct.

@mindplay-dk thoughts on this?

Here's the problem: under Semantic Versioning, a published API cannot have BC breaks without a major version bump. Small though it is, changing `$next = null` to just `$next` is a BC break. Thus, making this change (which may actually be warranted) will require a bump from 1.0 to 2.0.

**Comment by mindplay-dk** [comment]
Right, `$next` should never be `null` - I don't think any middleware accounts for `$next` anyhow, in fact, I don't see how it even could, or even less so, why it should.

Two thoughts.
1. If you have to make a BC break, maybe it's worth considering fixing some of the "weird" API stuff, e.g. give semantic names to other (interface) methods rather than using `__invoke()` magic, which isn't descriptive in at least a couple of cases.
2. Maybe it's time someone wrote a (FIG) PSR and standardize on this middleware interface nonsense, so we can start writing PSR-7 middleware that doesn't just magically "work" (thanks to `__invoke()` magic) but actually "works" because it adheres to a defined interface.

**Comment by KorvinSzanto** [comment]
> Maybe it's time someone wrote a (FIG) PSR and standardize on this middleware interface nonsense

@mindplay-dk I brought that up recently, I'm not sure how much support there is for that at the moment.

**Comment by shadowhand** [comment]
@pmjones even if FIG doesn't want to take it up, maybe @friendsofphp would? I'm not actually sure who is involved with that group...

**Comment by elazar** [comment]
@pmjones Any progress on this? We'd like to use `Relay\MiddlewareInterface` in [Spark](https://github.com/sparkphp/Spark), but the present nullability of `$next` is causing compatibility issues. :cry:

**Comment by shadowhand** [comment]
@pmjones 

> require a bump from 1.0 to 2.0

Perhaps 1.0 was a little hasty? ;) If it was still at 0.x version there would be no problem.

**Comment by pmjones** [comment]
All right, I'm going to bite the bullet and branch 2.x-dev. The `$next` param will be non-nullable, and @mindplay-dk will get his `run()` methods.

**Comment by shadowhand** [comment]
Snarkiness aside, there's no problem with bumping to v2.0.

**Comment by elazar** [comment]
Side note re: FIG and a middleware PSR, I think their [present decision is to wait](https://groups.google.com/forum/#!topic/php-fig/_idBxaLoapY).

> Thus, let's leave this be at the moment.  We can collect more data on what  middleware approaches emerge and become common, and revisit this question  again in a year or so.  Let's give the market a chance to make up its mind first.

**Comment by pmjones** [comment]
> Perhaps 1.0 was a little hasty?

Didn't seem like it at the time; the primary issue, such as it was, was the formal interface signature and not the gentlemens'-agreement signature. Oh well.

**Comment by pmjones** [comment]
@renan Here's the deal: I'm going to branch 2.x-dev; when I do, please rebase this PR against that branch, and I can merge it at that time.

**Comment by pmjones** [comment]
@renan Done; please rebase against the 2.x branch, and I'll merge. Thanks for your patience.

**Comment by elazar** [comment]
@pmjones Any chance of also resolving relayphp/Relay.Middleware#12 with this next release?

**Comment by pmjones** [comment]
@elazar Yes.

**Comment by pmjones** [comment]
Merged this into 2.x instead of 1.x per 97f4061db9e39ca139691b78bcef8ce2ef1efcfb

**Pull request closed without merging**
