### PR TITLE
Test against PHP 8.0

### PR DESCRIPTION
**Pull request by jbboehr**
* Upgrade doctrine/coding-standard to 8.2
* Upgrade phpunit to 8.5
* Update psalm to 4.7
* ~~Drop PHP 7.1 from TravisCI~~

I took the liberty of ignoring a few rules and fixing a few others due to changes in the new coding standards version, feel free to request changes or whatever.

### CODE REVIEW

**Comment by jbboehr** [comment]
Looks like CI isn't currently running on your repo, here's mine: https://travis-ci.com/github/jbboehr/Relay.Relay/builds/222082215

**Comment by kevinsmith** [comment]
Hey @jbboehr, thanks for the contribution!

Unfortunately, we can't drop PHP 7.1 compatibility yet since that would require a major version bump, and since we need to maintain PHP 7.1 compatibility, we also can't upgrade to PHPUnit 8+ in the Relay 2.x branch. Could you please revert the changes that drop PHP 7.1 from the CI config and bumped the PHPUnit version number?

**Comment by cxj** [comment]
Do we need a 3.x branch to drop 7.1?  It's been End-Of-Life since 2019.

**Comment by kevinsmith** [comment]
Yup, any BC-breaking changes will need to go in a 3.x branch. We should probably plan that separately.

I was just trying to decouple the changes that could happen immediately versus the ones that would require a version bump. I'm happy to consider and merge in anything that's compatible with the 2.x branch for now. If the purpose of this PR is to add PHP 8 compatibility (even if it's just to the CI suite), then it may need to wait until we're ready to begin work on 3.x.

**Comment by kevinsmith** [comment]
To expand on this... Given the title, I realize the original purpose of this PR was to introduce PHP 8 compatibility, but the bulk of the work has been toward upgrading Doctrine Coding Standard. _That_ is something we could merge into 2.x relatively soon, as long as we remove the separate changes that would require a version bump.

**Comment by jbboehr** [comment]
There were no code changes preventing 7.1 support, only the fact that there was no single release of phpunit that supported PHP 7.1 and PHP 8.0. I've expanded the version constraint on phpunit which will allow continued testing on 7.1.

**Comment by kevinsmith** [comment]
Awesome, thank you @jbboehr! Merging this in...

**Pull request merged**
