### PR TITLE
support psr/http-message v2

### LINKED ISSUE #58: `psr/http-message` v2 is not supported
They have added explicit return types to the HTTP message interfaces in `psr/http-message` v2. I believe this does not impact this library, and both versions can be simply allowed in the `composer.json`.

### PR DESCRIPTION
**Pull request by someniatko**
should fix #58

### CODE REVIEW

**Comment by kevinsmith** [comment]
@someniatko Sorry for the radio silence, I thought I responded to this shortly after you posted the PR but clearly I didn't.

We can't accept this at the moment because the project needs a PHP version bump first. I'm planning on doing that as part of some cleanup soon (which I why I realized I hadn't responded), so hang tight while I'm doing that. Thanks!

**Comment by mlahargou** [comment]
Hey there! Any update on this? It's blocking us from upgrading other packages currently.

**Comment by kevinsmith** [comment]
> Hey there! Any update on this? It's blocking us from upgrading other packages currently.

Working on putting together a release candidate now that would change the minimum necessary to get this to work. Would that work for you?

**Comment by kevinsmith** [comment]
@someniatko Mind updating your branch with the latest from the new base branch?

**Comment by kevinsmith** [comment]
> @someniatko Mind updating your branch with the latest from the new base branch?

Just nudging to see if you could merge in the base branch please. I'm happy to close this and take care of it on my end if you want, I just didn't want to take over your contribution.

**Comment by someniatko** [comment]
Hi guys, sorry for the delay. Rebased!

**Comment by kevinsmith** [comment]
Support for PSR-7's v2 interfaces is now available in Relay v3.

**Pull request merged**
