### PR TITLE
Use RequestInterface instead of ServerRequestInterface

### PR DESCRIPTION
**Pull request by pmjones**
This allows for both server-ish and client-ish usage.

### CODE REVIEW

**Comment by pmjones** [comment]
@shadowhand: review on this should be super-easy ;-)

**Comment by shadowhand** [comment]
:+1: totally obvious change, makes perfect sense for using Relay for HTTP queues.

**Comment by pmjones** [comment]
Right on. Next transition is a little tougher given the rename. Will try to make it as obvious as possible.

**Comment by shadowhand** [comment]
@pmjones can you do the queue before the rename? Seems like you could use a `while` loop instead of `array_shift`?

**Pull request merged**
