### PR TITLE
Fix #51

### LINKED ISSUE #51: zendframework/zend-diactoros has been abandoned
`require-dev` dependency `zendframework/zend-diactoros` has been abandoned.  The recommended replacement is `laminas/laminas-diactoros`.  Note that the replacement requires PHP 7.1 or later.

### PR DESCRIPTION
**Pull request by cxj**
Replaces abandoned package with a supported copy to fix issue #51 .

### CODE REVIEW

**Comment by kevinsmith** [comment]
Hey @cxj, thanks for tackling this. My apologies it took so long to respond. I've had some personal things to deal with lately.

I think it's best to keep things as much the same as possible for this change, given that the only real goal here is to fix the "abandoned" message when doing a Composer install. That would mean leaving the PHP constraint in place and keeping a `~1.0` version for `laminas/laminas-diactoros`. Otherwise we're unintentionally making a pretty massive requirements bump for package users.

**Comment by cxj** [comment]
Hey Kevin,  Would you entertain the idea of creating a new version branch (3.x) that would take the newer `~2` version for `laminas/laminas-diactoros`?   If so, I'll split this into 2 PRs, one for each branch and follow your suggestions.

**Comment by pmjones** [comment]
Alternatively, you may wish to consider using Guzzle; IIRC, it too now has an implementation of ServerRequestInterface.

**Comment by kevinsmith** [comment]
Certainly open to updating all the dependencies. But whether or not it would require a major version bump, that sort of change would definitely need to be in another PR.

Just curious @cxj, other than generally keeping things up to date, is there a particular benefit you're looking for that the newer version of diactoros brings?

**Comment by cxj** [comment]
I have supported applications and on-going development on those applications which use `radar/adr` and hence, its dependencies.  Those apps are being migrated to PHP 7.4 as well.  I've tested against `laminas/laminas-diactoros` at version `2.2.2`.

So, for me, using versions `~1.0` would mean some retesting and verification work.  

Also, generally speaking, it worries me to be significant release behind where work is being done on a project as it tends to imply less maintenance support (but not necessarily, of course) for older releases.

Both factors may be totally irrelevant in the case of `laminas/laminas-diactoros`.  I just am making my first effort towards the path of least effort.  :-)

**Comment by kevinsmith** [comment]
Gotcha. I'm devoting time today to get things up to date for Relay, so I'll have a look at all that. Hang tight on another PR to update diactoros though. I want to dig in a little to see if it's still the best choice for that dev dependency. (And also, given it's a dev dependency, it shouldn't affect production for projects that depend on Relay anyway.)

**Comment by cxj** [comment]
Ah, good point on the dev dependency.  It is a real dependency in my application, but not directly in Relay.  Thanks much for the attention to the project.

**Comment by kevinsmith** [comment]
Went ahead and made the abandoned package replacement in the main branch so I could get a release out the door today. Thanks for your heads up about this, @cxj!

**Comment by kevinsmith** [comment]
Just FYI, the Diactoros dev dependency is updated as of c9dcb934343ccd4c24ea6130b7f521be6fe81212.

**Pull request closed without merging**
